version: '3.3'

services:
  pygeoapi:
    image: geopython/pygeoapi:latest

    container_name: pygeoapi_mongo

    entrypoint:
      - /mongo-entrypoint.sh

    ports:
      - 5001:80

    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/local.config.yml
      - ./pygeoapi/mongo-entrypoint.sh:/mongo-entrypoint.sh
      - ./pygeoapi/wait-for-mongo.sh:/wait-for-mongo.sh
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    #restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      #- ./data:/data/db
      - ./docker-entrypoint-initdb.d/add_data.sh:/docker-entrypoint-initdb.d/add_data.sh:ro
      - ./mongo_data/:/mongo_data
    environment:
        MONGO_INITDB_DATABASE: mongodb
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #   ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/



volumes:
  mongo_data: {}